doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        dql:
            string_functions:
                # Add any DQL functions here
                FIELD: DoctrineExtensions\Query\Mysql\Field
                GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
            numeric_functions:
                # Add any numeric functions here
                MOD: DoctrineExtensions\Query\Mysql\Mod
            datetime_functions:
                # Add any datetime functions here
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat

        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
